<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Student;
use App\Models\Governate;
use App\Models\EducationalAdministration;
use App\Models\School;
use App\Models\Specialization;

class StudentSeeder extends Seeder
{
    public function run(): void
    {
        // Create a user (Student)
        $user = User::create(
            [
                [
                    'name' => 'احمد مجاهد ابوالخير محمود عرفه',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عمر وليد محمد صلاح الدين مدبولى',
                    'email' => 'omarmahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمود السيد مصطفى حسب الله',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'روان سامح موسي محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'حنين اشرف رجب عبدالغنى محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'شهد تامر سمير سيد ابراهيم',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'منه سمير حجازى مبروك بعرور',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'هنا احمد اسامه احمد سلام',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'رويدا طارق محمد توفيق',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ملك جمال فؤاد عبدالوهاب',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ايمن فتحى موسى دويب',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'بولا عماد زكى مجلى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'حسن قرنى حسن رجب',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ربيع ميهوب تعلب حسين',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد عبدالله احمد عبدالفتاح',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد عبدالله محمود عبدالله',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'اسلام محمود مفرج محمود',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد رمضان عبدالمحسن عبدالجواد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد صبيح قرني محمود',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمود احمد عبدالحميد قرني',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'مصطفى عشري عاطف عبدالموجود',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'حبيبه شعبان ابراهيم نصر',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'شهد عصام محمد عبدالهادي',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'منى عزت سعيد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد عبدالفتاح زكرياعبدالرازق الخولى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'جرجس كامل امين يوسف',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عادل على السعودى على محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'علاء عبدالقادر عبدالسميع محمود',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'مازن طارق رجب محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'مصطفى احمد صابر محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد محمود احمد حسينى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عزت محمد عزت ابوسريع',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'وسام ربيع ياسين محمد العمر',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'يوسف تامر فتحي عبدربه',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'رمضان محمد محمود المرسى الجوهرى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمود نادر محمود امام',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'يوسف مصطفى محمود غنيم اسماعيل',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد طارق محمد محمود',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'راضي محمود عزت ابوسريع درويش',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'زياد محمد محمود عويس',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عمار ناصر عبدالمنعم عبدالسلام',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عمر سالم رمضان سالم',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمود مصطفى محمود طه محمد الاسناوى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ايه سعيد احمد مصطفى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'رحاب حمدي احمد محمد سعيد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'سما ياسر عاشور عثمان',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ليلى فكرى سيد احمد جاب الله ابوالمجد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'سيف محمد فوزى الغرباوى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'مصطفى محمد فوزي محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'حبيبه خالد سعيد محمد الصعيدى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ميار ابراهيم فتحى محمد عبداللطيف',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'يمنى صلاح عبدالعاطى متولى يوسف',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد سيد حنفى راوى عبدالعال',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'هدى ناصر سلامه محمود صالح',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'يوسف علي هلال علي',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'الاء محمد ابراهيم محمد القللي',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'امنيه عماد عيد عبدالوهاب عبدالحميد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'بسمله عبدالله السيد اسماعيل الحاوي',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'سماء سمير احمد علي احمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ناهد فتحى على ذكى البرعى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'هند مصطفى فوزى البغدادى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'اميره عبدالباسط جمال المهدى محمود',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'مروه صابر سليمان سليمان الصيرفي',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'منه الله محمد محمد زكى سلامه',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد علاءالدين سمير عبدالغنى عطيه',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عمر احمد مهنى عبدالعظيم',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'رحمه احمد محمد عبدالباقي',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'منه مبروك علي احمد علي',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد ايمن رشاد محمد خطاب',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عبدالله محمد عبدالله محمد ابوفراج',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد ابراهيم احمد ابراهيم يوسف',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمود عبدالرازق عباس رجب محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'مصطفى احمد مصطفى الجعيصي',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'يوسف هاني مصطفى رمضان محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'شمس السيد محمد احمد الطنطاوي',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد محمد احمد حسن محمد غازى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد ياسر محمود عبدالغني محمود ابوشلبي',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'اسلام عادل شعبان رشوان موسي',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'اسلام مجدي رشاد ابراهيم مصطفي',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عبدالرحمن محمد سمير السيد حجازى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'الاء اشرف فاروق على محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'شهد احمد رمضان احمد سعد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'شهد خالد عادل ذكي',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'هبه ربيع السيد ربيع السيد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد عيد رمضان عبدالمعطى يوسف',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ايه حماده على محمد على',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'مصطفى عبدالهادى صالح قطب عباس',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'كريم ياسر السيد مهدى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'هادى مجدى ابوالعلا رشاد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'اسراء ناصر احمد محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'زياد محمد مصيلحى ربيع',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'لوجين مصطفى محمود احمد الصياد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'مريم ابراهيم احمد محمد زيتون',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'فرح حسام محمد عزالدين عبدالعظيم الغمري',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ليلى محمد حماده صميده محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ملك احمد محمود زينهم عبدالمعطى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'نورالدين احمد كمال عبدالباقى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'مصطفى طارق عبدالفتاح حسن',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'سلمى احمد كمال عبدالباقى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ادهم هيثم فتحى محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'سيف الدين ياسر عزت ابراهيم',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عبدالله ابوبكر حسن ابوبكر',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عمر سيد محمد جلال',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد احمد ماهر احمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد هشام محمد سيد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد ممدوح حسن محمود',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد حسام محمد سيد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد لدهم دسوقى شحات',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'زياد محمد احمد سعيد محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد سامح ابراهيم حسين حسانين',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عبدالرحمن يوسف سعد على',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'يوسف هشام سيد حميده',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عبدالرحمن محمد رفعت محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد خالد سلامه محمود',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'يوسف احمد شوقى عبدالعزيز',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'خالد لدهم دسوقى شحات',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عبدالله فريد عبدالله محمد السيد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد احمد محمد عبدالمنعم',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد شريف عبدالعظيم محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ياسين اسامه عبدالعزيز سيد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد خالد ابوالمجد احمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد محمد عطيه محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'زياد هاني ابراهيم محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد عادل عبدالله محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'مصطفى محمد مصطفى سيد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'يوسف رمضان يحى عبدالله',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'كنزى وليد رضا امام على',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'لمى وائل سمير السيد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'روان حامد اليمانى سلام',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'حبيبه سامح عطيه حسين',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ساره محمد فتحى عبدالرحمن',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'سما محمد ذكى على',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'لجين يونس احمد سيد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'جني حسني كمال محفوظ',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'جنى عمادالدين عبدالباقى عبدالغفار',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'رنا حسن ابراهيم عثمان',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ساره ايهاب عبدالحميد اسماعيل',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'فاطمه محمود السيد محمود السيد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'نورهان انور رمضان مصطفى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'هنا سامح ابراهيم محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'مريم حسام محمد محمود',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'مريم احمد السيد شحاته',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'نور وليد رشاد عبدالمقصود',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'بلال مجدى حمدان احمد موسى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'خالد وليد ابراهيم محمد كريم',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'يوسف على السيد محمد السيد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد تامر احمد محمد رفاعى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد عصام محمد ابواليزيد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عصام خالد عبدالتواب يونس',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'منه مصطفى فاروق محمد يس',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'وعد محمود احمد عبدالسميع',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد احمد عبدالهادى سعد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد عادل محمد خليل',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'حمزه يحيى جلال يحيى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'على عبدالحكيم احمد عباده عوض',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'اياد رفعت محمد رضا',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'زياد وليد حنفى عثمان ياسين',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'جنى احمد اسماعيل احمد اسماعيل',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'نور احمد السيد يوسف محمد عفيفي',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'نور حسين فتحى حسين',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'حلا محمود محمد الصادق محمد عبدالمتعال',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'حسن محمد محمود احمد نورالدين',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ميرنا ايمن امين طه ابوالعلا',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'فيروزه حسام مؤنس محمد سعد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد محمد السيد طلبه امام',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'يوسف محمد علاء خليل مصطفى عامر',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عبدالرحمن محمود زكى محمود الجابرى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عبدالرحمن وائل فائق عرفه',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد حسن محمد على على ابوحسين',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد رمضان فوزى محمد بيبرس',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'جنى طارق عطيه محمد عطيه',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'سيف الدين محمد زكريا عبدالرازق على',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عبدالله عماد فوزى حسن عبدالحليم عمر',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عبدالله هشام عبدالصادق ابراهيم',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'موسى محسن عياد الياس',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'على عبدالرحمن محمد ابراهيم حمزه',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'انجي هانىء عبدالصمد محمد عبدالواحد الدقدوقى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ياسمين معتز مصطفى محمود',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'يارا محمد عماد عصمت نورالدين عصمت احمد عصمت',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد صالح عبدالستار عبدالغفار',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'رامى زاهر محمد ابراهيم',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد ماهر حسن على',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عبدالرحمن حسام ابراهيم الصادق',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'مروان محمد عبدربه درويش المعصراوى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد ياسر محمدين بيومى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'رنا محمد احمد عبدالله',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'مايا محمد سعدالدين محمد محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمود طه محمود احمد دسوقى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عيسى على احمد محمد حزين',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'فرح محمد محمود بسيوني عبدالفتاح',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'رؤى محمد عيد محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد جمال شحاته محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'مروان اسماعيل محمود عبدالعظيم',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'روان محمد على محمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'منه الله حسام محمد احمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد محمد عبد الرحمن مصطفى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'نورهان نبيل عبد العظيم صالح',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'يوسف عماد محمد عزت عبدالحميد الالفى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'امل محمد وجدى عبدالحميد المنصورى',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'حبيبه احمد عبدالسميع احمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عمر محمد احمد محمد هلال',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'ندى رمضان عبدالونيس محمد الدمهوجي',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'احمد تامر صلاح الدين يوسف',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'محمد هاني سعيد محمد محمود',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],
                [
                    'name' => 'عمر ضياء فاوى احمد',
                    'email' => 'omar.mahmoud@gmail.com',
                    'password' => bcrypt('student123'),
                    'role' => 'student',
                ],


            ]
        );







        // Fetch required related data (randomized for realism)
        $governate = Governate::inRandomOrder()->first();
        $administration = EducationalAdministration::where('governate_id', $governate->id)->inRandomOrder()->first();
        $school = School::where('educational_administration_id', $administration->id)->inRandomOrder()->first();
        $specialization = Specialization::where('name', 'Scientific Science')->first(); // علمى علوم

        // Create a student linked to the user
        Student::create([
            'seat_number' => rand(100000, 199999), // Realistic seat number
            'user_id' => $user->id,
            'grade' => rand(300, 410), // Randomized for realism (Out of 410)
            'governate_id' => $governate->id,
            'educational_administration_id' => $administration->id,
            'school_id' => $school->id,
            'specialization_id' => $specialization->id,
            'phone_number' =>'01'. rand(0,2). rand(10000000, 99999999) , // Realistic Egyptian phone number
            'national_id' => rand(20000000000000, 20009999999999), // Random 14-digit ID
            'gender' => 'ذكر',
            'date_of_birth' =>'2007-'.rand(00,12).'-'. rand(00,28), // Typical final-year student birth year
            'address' => '25 Tahrir Street, ' . $governate->name,
        ]);
    }
}
